from distutils.core import setup

setup(
    name='bosco',
    version='0.2dev',
    author='Gaudenz Steinlin',
    author_email='gaudenz@durcheinandertal.ch',
    packages=['bosco',
              'bosco.test',
              ],
    scripts=['bin/autoreader',
             'bin/bosco',
             'bin/import',
             'bin/print',
             'bin/ranking_viewer',
             'bin/ranking_export',
             'bin/solvexport',
             'bin/speaker',
             ],
    package_data={'bosco': ['templates/*.html',
                            'templates/*.tex',
                            ]},
    url='http://bosco.durcheinandertal.ch/',
    license='LICENSE.txt',
    description='Free orienteering framework',
    long_description=open('README.txt').read(),
    install_requires=[
        'storm',
        'wxPython',
        'pyserial',
        'reportlab',
        'Mako',
        ],
)
