# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.0.1 on Sat Jun 12 12:55:50 2021
#

import wx

import wx.grid

from bosco.gui.wxutil import EditingPanel
from bosco.gui.wxutil import BaseRunPanel
from bosco.gui.wxutil import RunSearchWidget


class RunEditorFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((636, 1028))
        self.SetTitle("Run Editor")

        # Menu Bar
        self.main_frame_menubar = wx.MenuBar()
        self.file = wx.Menu()
        self.file.Append(wx.ID_EXIT, "", "")
        self.Bind(wx.EVT_MENU, self.Quit, id=wx.ID_EXIT)
        self.main_frame_menubar.Append(self.file, "&File")
        self.settings = wx.Menu()
        self.main_frame_menubar.connect_reader = self.settings.Append(wx.ID_ANY, "&Connect SI-Reader", "")
        self.Bind(wx.EVT_MENU, self.ConnectReader, self.main_frame_menubar.connect_reader)
        self.main_frame_menubar.print_command = self.settings.Append(wx.ID_ANY, "&Print command", "")
        self.Bind(wx.EVT_MENU, self.SetPrintCommand, self.main_frame_menubar.print_command)
        self.main_frame_menubar.Append(self.settings, "&Settings")
        self.SetMenuBar(self.main_frame_menubar)
        # Menu Bar end

        self.statusbar = self.CreateStatusBar(2)
        self.statusbar.SetStatusWidths([-1, 250])
        # statusbar fields
        statusbar_fields = ["Waiting for SI-Card...", "/dev/ttyUSB0 (at 38400 baud)"]
        for i in range(len(statusbar_fields)):
            self.statusbar.SetStatusText(statusbar_fields[i], i)
        self.Layout()


    def Quit(self, event):
        print("Event handler 'Quit' not implemented!")
        event.Skip()

    def ConnectReader(self, event):
        print("Event handler 'ConnectReader' not implemented!")
        event.Skip()

    def SetPrintCommand(self, event):
        print("Event handler 'SetPrintCommand' not implemented!")
        event.Skip()


class TeamPanel(EditingPanel):
    def __init__(self, *args, **kwds):
        kwds["style"] = kwds.get("style", 0) | wx.TAB_TRAVERSAL
        EditingPanel.__init__(self, *args, **kwds)

        sizer_20 = wx.BoxSizer(wx.VERTICAL)

        self.searchbox = wx.SearchCtrl(self, wx.ID_ANY, "")
        self.searchbox.ShowCancelButton(True)
        self.searchbox.SetDescriptiveText("Search Team")
        sizer_20.Add(self.searchbox, 0, wx.EXPAND, 0)

        self.searchresults = wx.ListCtrl(self, wx.ID_ANY, style=wx.LC_HRULES | wx.LC_REPORT | wx.LC_SINGLE_SEL | wx.LC_VRULES)
        self.searchresults.AppendColumn("ID", format=wx.LIST_FORMAT_LEFT, width=40)
        self.searchresults.AppendColumn("Number", format=wx.LIST_FORMAT_LEFT, width=80)
        self.searchresults.AppendColumn("Name", format=wx.LIST_FORMAT_LEFT, width=300)
        self.searchresults.AppendColumn("Category", format=wx.LIST_FORMAT_LEFT, width=80)
        sizer_20.Add(self.searchresults, 1, wx.EXPAND, 0)

        sizer_21 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_20.Add(sizer_21, 0, wx.EXPAND, 0)

        label_6_copy_2 = wx.StaticText(self, wx.ID_ANY, "Team Validation:")
        sizer_21.Add(label_6_copy_2, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 5)

        self.validation = wx.StaticText(self, wx.ID_ANY, "not yet finished")
        self.validation.SetForegroundColour(wx.Colour(255, 0, 0))
        self.validation.SetFont(wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        sizer_21.Add(self.validation, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 5)

        self.label_9 = wx.StaticText(self, wx.ID_ANY, "Team Score:")
        sizer_21.Add(self.label_9, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 5)

        self.score = wx.StaticText(self, wx.ID_ANY, "Runs: 41, Time:23:34:76")
        self.score.SetFont(wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        sizer_21.Add(self.score, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 5)

        self.run_grid = wx.grid.Grid(self, wx.ID_ANY, size=(1, 1))
        self.run_grid.CreateGrid(0, 10)
        self.run_grid.EnableEditing(0)
        self.run_grid.EnableDragColSize(0)
        self.run_grid.EnableDragRowSize(0)
        self.run_grid.EnableDragGridSize(0)
        self.run_grid.SetColLabelValue(0, "Run ID")
        self.run_grid.SetColLabelValue(1, "Course")
        self.run_grid.SetColLabelValue(2, "Runner")
        self.run_grid.SetColLabelValue(3, "SI-Card")
        self.run_grid.SetColLabelValue(4, "Team")
        self.run_grid.SetColLabelValue(5, "Start")
        self.run_grid.SetColLabelValue(6, "Finish")
        self.run_grid.SetColLabelValue(7, "Validation")
        self.run_grid.SetColLabelValue(8, "Team Validation")
        self.run_grid.SetColLabelValue(9, "Score")
        sizer_20.Add(self.run_grid, 1, wx.EXPAND, 0)

        self.SetSizer(sizer_20)
        sizer_20.Fit(self)

        self.Layout()

        self.Bind(wx.EVT_LIST_ITEM_ACTIVATED, self.SetTeam, self.searchresults)

    def SetTeam(self, event):
        print("Event handler 'SetTeam' not implemented!")
        event.Skip()


class RunPanel(BaseRunPanel):
    def __init__(self, *args, **kwds):
        kwds["style"] = kwds.get("style", 0) | wx.TAB_TRAVERSAL
        BaseRunPanel.__init__(self, *args, **kwds)

        sizer_5 = wx.BoxSizer(wx.VERTICAL)

        self.window_1 = wx.SplitterWindow(self, wx.ID_ANY, style=wx.SP_3D | wx.SP_BORDER)
        self.window_1.SetMinimumPaneSize(20)
        sizer_5.Add(self.window_1, 1, wx.EXPAND, 0)

        self.window_1_pane_1 = wx.Panel(self.window_1, wx.ID_ANY)

        sizer_13 = wx.BoxSizer(wx.HORIZONTAL)

        sizer_30 = wx.StaticBoxSizer(wx.StaticBox(self.window_1_pane_1, wx.ID_ANY, "Select Run"), wx.VERTICAL)
        sizer_13.Add(sizer_30, 1, wx.EXPAND, 0)

        self.searchbox = RunSearchWidget(self.window_1_pane_1, wx.ID_ANY)
        sizer_30.Add(self.searchbox, 0, wx.ALL | wx.EXPAND, 3)

        self.searchresults = wx.ListCtrl(self.window_1_pane_1, wx.ID_ANY, style=wx.BORDER_SUNKEN | wx.LC_REPORT | wx.LC_SINGLE_SEL)
        sizer_30.Add(self.searchresults, 1, wx.ALL | wx.EXPAND, 3)

        sizer_19 = wx.BoxSizer(wx.VERTICAL)
        sizer_13.Add(sizer_19, 0, wx.EXPAND, 0)

        self.rollback = wx.Button(self.window_1_pane_1, wx.ID_REFRESH, "")
        sizer_19.Add(self.rollback, 0, wx.ALL | wx.EXPAND, 2)

        self.delete = wx.Button(self.window_1_pane_1, wx.ID_DELETE, "")
        sizer_19.Add(self.delete, 0, wx.ALL | wx.EXPAND, 2)

        self.add_button = wx.Button(self.window_1_pane_1, wx.ID_ADD, "")
        sizer_19.Add(self.add_button, 0, wx.ALL | wx.EXPAND, 2)

        self.registration = wx.CheckBox(self.window_1_pane_1, wx.ID_ANY, "Registration mode")
        sizer_19.Add(self.registration, 0, wx.ALL, 2)

        self.print_button = wx.Button(self.window_1_pane_1, wx.ID_PRINT, "")
        sizer_19.Add(self.print_button, 0, wx.ALL | wx.EXPAND, 2)

        self.window_1_pane_2 = wx.Panel(self.window_1, wx.ID_ANY)

        sizer_2 = wx.BoxSizer(wx.VERTICAL)

        sizer_9 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_2.Add(sizer_9, 0, wx.EXPAND, 0)

        sizer_8 = wx.StaticBoxSizer(wx.StaticBox(self.window_1_pane_2, wx.ID_ANY, "Runner"), wx.VERTICAL)
        sizer_9.Add(sizer_8, 0, wx.ALL | wx.EXPAND, 5)

        label_2 = wx.StaticText(self.window_1_pane_2, wx.ID_ANY, "Change Runner:")
        sizer_8.Add(label_2, 0, wx.LEFT | wx.RIGHT | wx.TOP, 10)

        self.run_runner_combo = wx.ComboBox(self.window_1_pane_2, wx.ID_ANY, choices=[], style=wx.CB_DROPDOWN | wx.CB_READONLY)
        self.run_runner_combo.SetMinSize((250, 27))
        sizer_8.Add(self.run_runner_combo, 0, wx.LEFT | wx.RIGHT, 10)

        sizer_8.Add((20, 5), 0, wx.ALL, 0)

        sizer_7 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_8.Add(sizer_7, 0, wx.ALL | wx.EXPAND, 2)

        sizer_31 = wx.BoxSizer(wx.VERTICAL)
        sizer_7.Add(sizer_31, 1, wx.EXPAND, 0)

        label_20_copy = wx.StaticText(self.window_1_pane_2, wx.ID_ANY, "Number:")
        sizer_31.Add(label_20_copy, 0, wx.ALL, 0)

        self.runner_number = wx.TextCtrl(self.window_1_pane_2, wx.ID_ANY, "101A")
        self.runner_number.SetMinSize((122, 25))
        sizer_31.Add(self.runner_number, 0, wx.ALL, 0)

        sizer_32 = wx.BoxSizer(wx.VERTICAL)
        sizer_7.Add(sizer_32, 1, wx.EXPAND, 0)

        self.label_1 = wx.StaticText(self.window_1_pane_2, wx.ID_ANY, "Category:")
        sizer_32.Add(self.label_1, 0, wx.ALL, 0)

        self.runner_category = wx.TextCtrl(self.window_1_pane_2, wx.ID_ANY, "")
        self.runner_category.SetMinSize((122, 25))
        sizer_32.Add(self.runner_category, 0, wx.ALL, 0)

        sizer_8.Add((20, 5), 0, wx.ALL, 2)

        label_20 = wx.StaticText(self.window_1_pane_2, wx.ID_ANY, "Runner:")
        sizer_8.Add(label_20, 0, wx.ALL, 2)

        sizer_28 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_8.Add(sizer_28, 0, wx.ALL | wx.EXPAND, 2)

        self.runner_given_name = wx.TextCtrl(self.window_1_pane_2, wx.ID_ANY, "Gaudenz")
        self.runner_given_name.SetMinSize((122, 25))
        sizer_28.Add(self.runner_given_name, 0, wx.ALL, 0)

        self.runner_surname = wx.TextCtrl(self.window_1_pane_2, wx.ID_ANY, "Steinlin")
        self.runner_surname.SetMinSize((122, 25))
        sizer_28.Add(self.runner_surname, 0, wx.ALL, 0)

        sizer_29 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_8.Add(sizer_29, 0, wx.EXPAND, 0)

        self.label_4 = wx.StaticText(self.window_1_pane_2, wx.ID_ANY, "Date of birth:")
        sizer_29.Add(self.label_4, 0, wx.ALIGN_CENTER_VERTICAL | wx.BOTTOM | wx.LEFT | wx.TOP, 2)

        self.runner_dateofbirth = wx.TextCtrl(self.window_1_pane_2, wx.ID_ANY, "1975-10-05")
        self.runner_dateofbirth.SetMinSize((90, 25))
        sizer_29.Add(self.runner_dateofbirth, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 2)

        sizer_8.Add((20, 5), 0, wx.ALL, 2)

        label_22 = wx.StaticText(self.window_1_pane_2, wx.ID_ANY, "Team:")
        sizer_8.Add(label_22, 0, wx.ALL, 2)

        self.runner_team = wx.ComboBox(self.window_1_pane_2, wx.ID_ANY, choices=[], style=wx.CB_DROPDOWN | wx.CB_READONLY)
        self.runner_team.SetMinSize((250, 27))
        sizer_8.Add(self.runner_team, 0, wx.ALL, 1)

        sizer_8.Add((20, 5), 0, wx.ALL, 2)

        label_22_copy = wx.StaticText(self.window_1_pane_2, wx.ID_ANY, "Club:")
        sizer_8.Add(label_22_copy, 0, wx.ALL, 2)

        self.runner_club = wx.TextCtrl(self.window_1_pane_2, wx.ID_ANY, "UBOL")
        sizer_8.Add(self.runner_club, 0, wx.ALL | wx.EXPAND, 2)

        sizer_2_copy = wx.StaticBoxSizer(wx.StaticBox(self.window_1_pane_2, wx.ID_ANY, "Run"), wx.HORIZONTAL)
        sizer_9.Add(sizer_2_copy, 0, wx.ALL | wx.EXPAND, 5)

        sizer_4 = wx.BoxSizer(wx.VERTICAL)
        sizer_2_copy.Add(sizer_4, 0, wx.EXPAND, 0)

        sizer_27 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_4.Add(sizer_27, 0, wx.EXPAND, 0)

        label_24_copy_copy_copy_copy = wx.StaticText(self.window_1_pane_2, wx.ID_ANY, "Run ID:")
        sizer_27.Add(label_24_copy_copy_copy_copy, 0, wx.ALL, 0)

        self.run_id = wx.StaticText(self.window_1_pane_2, wx.ID_ANY, "1234")
        sizer_27.Add(self.run_id, 0, wx.ALL, 2)

        sizer_4.Add((10, 5), 0, 0, 0)

        label_3 = wx.StaticText(self.window_1_pane_2, wx.ID_ANY, "Course Code:")
        sizer_4.Add(label_3, 0, wx.ALL, 0)

        self.course = wx.TextCtrl(self.window_1_pane_2, wx.ID_ANY, "LDN1", style=wx.TE_PROCESS_ENTER)
        self.course.SetMinSize((150, 25))
        sizer_4.Add(self.course, 0, wx.ALL, 0)

        sizer_4.Add((10, 5), 0, 0, 0)

        self.label_12 = wx.StaticText(self.window_1_pane_2, wx.ID_ANY, "Manual start time:")
        sizer_4.Add(self.label_12, 0, 0, 0)

        self.manual_start_time = wx.TextCtrl(self.window_1_pane_2, wx.ID_ANY, "")
        self.manual_start_time.SetMinSize((150, 25))
        sizer_4.Add(self.manual_start_time, 0, 0, 0)

        sizer_4.Add((10, 5), 0, 0, 0)

        self.label_13 = wx.StaticText(self.window_1_pane_2, wx.ID_ANY, "Manual finish time:")
        sizer_4.Add(self.label_13, 0, 0, 0)

        self.manual_finish_time = wx.TextCtrl(self.window_1_pane_2, wx.ID_ANY, "")
        self.manual_finish_time.SetMinSize((150, 25))
        sizer_4.Add(self.manual_finish_time, 0, 0, 0)

        sizer_2_copy.Add((20, 20), 0, 0, 0)

        sizer_10 = wx.BoxSizer(wx.VERTICAL)
        sizer_2_copy.Add(sizer_10, 0, wx.EXPAND, 0)

        self.override = wx.RadioBox(self.window_1_pane_2, wx.ID_ANY, "Override Validation", choices=["no override", "OK", "not completed", "missing controls", "did not finish", "did not start"], majorDimension=6, style=wx.RA_SPECIFY_ROWS)
        self.override.SetSelection(0)
        sizer_10.Add(self.override, 0, wx.ALL, 2)

        self.complete = wx.CheckBox(self.window_1_pane_2, wx.ID_ANY, "Run complete")
        self.complete.SetValue(1)
        sizer_10.Add(self.complete, 0, wx.ALL, 2)

        sizer_24 = wx.BoxSizer(wx.VERTICAL)
        sizer_9.Add(sizer_24, 0, wx.ALL | wx.EXPAND, 0)

        sizer_25 = wx.StaticBoxSizer(wx.StaticBox(self.window_1_pane_2, wx.ID_ANY, "Validation and Scoreing"), wx.HORIZONTAL)
        sizer_24.Add(sizer_25, 0, wx.ALL | wx.EXPAND, 5)

        sizer_6_copy = wx.BoxSizer(wx.VERTICAL)
        sizer_25.Add(sizer_6_copy, 0, wx.EXPAND, 0)

        label_4_copy_1 = wx.StaticText(self.window_1_pane_2, wx.ID_ANY, "Run Validation:")
        sizer_6_copy.Add(label_4_copy_1, 0, wx.ALL, 0)

        label_6_copy_3 = wx.StaticText(self.window_1_pane_2, wx.ID_ANY, "Team Validation:")
        sizer_6_copy.Add(label_6_copy_3, 0, wx.ALL, 0)

        label_6_copy_copy_1 = wx.StaticText(self.window_1_pane_2, wx.ID_ANY, "Score:")
        sizer_6_copy.Add(label_6_copy_copy_1, 0, wx.ALL, 0)

        label_6_copy_copy_copy_copy_copy = wx.StaticText(self.window_1_pane_2, wx.ID_ANY, "Team Score:")
        sizer_6_copy.Add(label_6_copy_copy_copy_copy_copy, 0, wx.ALL, 0)

        sizer_23 = wx.BoxSizer(wx.VERTICAL)
        sizer_25.Add(sizer_23, 0, wx.EXPAND, 0)

        self.run_validation = wx.StaticText(self.window_1_pane_2, wx.ID_ANY, "OK")
        self.run_validation.SetForegroundColour(wx.Colour(0, 255, 0))
        sizer_23.Add(self.run_validation, 0, wx.ALL, 0)

        self.team_validation = wx.StaticText(self.window_1_pane_2, wx.ID_ANY, "not yet finished")
        self.team_validation.SetForegroundColour(wx.Colour(255, 0, 0))
        sizer_23.Add(self.team_validation, 0, wx.ALL, 0)

        self.run_score = wx.StaticText(self.window_1_pane_2, wx.ID_ANY, "1:05:23")
        sizer_23.Add(self.run_score, 0, wx.ALL, 0)

        self.team_score = wx.StaticText(self.window_1_pane_2, wx.ID_ANY, "Runs: 21, Time: 9:04:32")
        sizer_23.Add(self.team_score, 0, wx.ALL, 0)

        sizer_26 = wx.StaticBoxSizer(wx.StaticBox(self.window_1_pane_2, wx.ID_ANY, "SI-Card Times"), wx.HORIZONTAL)
        sizer_24.Add(sizer_26, 1, wx.ALL | wx.EXPAND, 5)

        sizer_6 = wx.BoxSizer(wx.VERTICAL)
        sizer_26.Add(sizer_6, 0, wx.EXPAND, 0)

        label_24 = wx.StaticText(self.window_1_pane_2, wx.ID_ANY, "SI-Card:")
        sizer_6.Add(label_24, 0, wx.ALL, 0)

        label_26 = wx.StaticText(self.window_1_pane_2, wx.ID_ANY, "Readout time:")
        sizer_6.Add(label_26, 0, wx.ALL, 0)

        self.label_5 = wx.StaticText(self.window_1_pane_2, wx.ID_ANY, "Clear time:")
        sizer_6.Add(self.label_5, 0, wx.ALL, 0)

        self.label_7 = wx.StaticText(self.window_1_pane_2, wx.ID_ANY, "Check time:")
        sizer_6.Add(self.label_7, 0, wx.ALL, 0)

        self.label_7_copy = wx.StaticText(self.window_1_pane_2, wx.ID_ANY, "Start time:")
        sizer_6.Add(self.label_7_copy, 0, wx.ALL, 0)

        self.label_7_copy_1 = wx.StaticText(self.window_1_pane_2, wx.ID_ANY, "Finish time:")
        sizer_6.Add(self.label_7_copy_1, 0, wx.ALL, 0)

        sizer_23_copy = wx.BoxSizer(wx.VERTICAL)
        sizer_26.Add(sizer_23_copy, 0, wx.EXPAND, 0)

        self.runner_sicard = wx.StaticText(self.window_1_pane_2, wx.ID_ANY, "7644523")
        sizer_23_copy.Add(self.runner_sicard, 0, wx.ALL, 0)

        self.readout_time = wx.StaticText(self.window_1_pane_2, wx.ID_ANY, "2008-05-04 12:00:54")
        sizer_23_copy.Add(self.readout_time, 0, wx.ALL, 0)

        self.clear_time = wx.StaticText(self.window_1_pane_2, wx.ID_ANY, "2008-05-04 11:02:54")
        sizer_23_copy.Add(self.clear_time, 0, wx.ALL, 0)

        self.check_time = wx.StaticText(self.window_1_pane_2, wx.ID_ANY, "2008-05-04 11:03:01")
        sizer_23_copy.Add(self.check_time, 0, wx.ALL, 0)

        self.card_start_time = wx.StaticText(self.window_1_pane_2, wx.ID_ANY, "2008-05-04 11:05:29")
        sizer_23_copy.Add(self.card_start_time, 0, wx.ALL, 0)

        self.card_finish_time = wx.StaticText(self.window_1_pane_2, wx.ID_ANY, "2008-05-04 11:58:01")
        sizer_23_copy.Add(self.card_finish_time, 0, wx.ALL, 0)

        sizer_16 = wx.StaticBoxSizer(wx.StaticBox(self.window_1_pane_2, wx.ID_ANY, "Punches"), wx.VERTICAL)
        sizer_2.Add(sizer_16, 1, wx.ALL | wx.EXPAND, 5)

        self.punches_grid = wx.grid.Grid(self.window_1_pane_2, wx.ID_ANY, size=(1, 1))
        self.punches_grid.CreateGrid(0, 7)
        self.punches_grid.EnableDragColSize(0)
        self.punches_grid.EnableDragRowSize(0)
        self.punches_grid.EnableDragGridSize(0)
        self.punches_grid.SetColLabelValue(0, "Nr.")
        self.punches_grid.SetColLabelValue(1, "Control")
        self.punches_grid.SetColLabelValue(2, "SI")
        self.punches_grid.SetColLabelValue(3, "Card Punchtime")
        self.punches_grid.SetColLabelValue(4, "Manual Punchtime")
        self.punches_grid.SetColLabelValue(5, "Ignore")
        self.punches_grid.SetColLabelValue(6, "")
        sizer_16.Add(self.punches_grid, 1, wx.ALL | wx.EXPAND, 5)

        self.window_1_pane_2.SetSizer(sizer_2)

        self.window_1_pane_1.SetSizer(sizer_13)

        self.window_1.SplitHorizontally(self.window_1_pane_1, self.window_1_pane_2)

        self.SetSizer(sizer_5)
        sizer_5.Fit(self)

        self.Layout()

        self.Bind(wx.EVT_LIST_ITEM_ACTIVATED, self.SetRun, self.searchresults)
        self.Bind(wx.EVT_LIST_ITEM_SELECTED, self.SetRun, self.searchresults)
        self.Bind(wx.EVT_BUTTON, self.Rollback, self.rollback)
        self.Bind(wx.EVT_BUTTON, self.DeleteRun, self.delete)
        self.Bind(wx.EVT_BUTTON, self.AddRun, self.add_button)
        self.Bind(wx.EVT_BUTTON, self.OnPrint, self.print_button)
        self.Bind(wx.EVT_COMBOBOX, self.SetRunRunner, self.run_runner_combo)
        self.Bind(wx.EVT_TEXT, self.FieldChanged, self.runner_number)
        self.Bind(wx.EVT_TEXT, self.FieldChanged, self.runner_category)
        self.Bind(wx.EVT_TEXT, self.FieldChanged, self.runner_given_name)
        self.Bind(wx.EVT_TEXT, self.FieldChanged, self.runner_surname)
        self.Bind(wx.EVT_TEXT, self.FieldChanged, self.runner_dateofbirth)
        self.Bind(wx.EVT_COMBOBOX, self.SetRunnerTeam, self.runner_team)
        self.Bind(wx.EVT_TEXT, self.FieldChanged, self.runner_club)
        self.Bind(wx.EVT_TEXT, self.SetCourse, self.course)
        self.Bind(wx.EVT_TEXT, self.FieldChanged, self.manual_start_time)
        self.Bind(wx.EVT_TEXT, self.FieldChanged, self.manual_finish_time)
        self.Bind(wx.EVT_RADIOBOX, self.SetOverride, self.override)
        self.Bind(wx.EVT_CHECKBOX, self.SetComplete, self.complete)
        self.Bind(wx.grid.EVT_GRID_CMD_CELL_CHANGED, self.ChangePunch, self.punches_grid)
        self.Bind(wx.grid.EVT_GRID_CMD_EDITOR_HIDDEN, self.ExitPunch, self.punches_grid)
        self.Bind(wx.grid.EVT_GRID_CMD_EDITOR_SHOWN, self.EditPunch, self.punches_grid)

    def SetRun(self, event):
        print("Event handler 'SetRun' not implemented!")
        event.Skip()

    def Rollback(self, event):
        print("Event handler 'Rollback' not implemented!")
        event.Skip()

    def DeleteRun(self, event):
        print("Event handler 'DeleteRun' not implemented!")
        event.Skip()

    def AddRun(self, event):
        print("Event handler 'AddRun' not implemented!")
        event.Skip()

    def OnPrint(self, event):
        print("Event handler 'OnPrint' not implemented!")
        event.Skip()

    def SetRunRunner(self, event):
        print("Event handler 'SetRunRunner' not implemented!")
        event.Skip()

    def FieldChanged(self, event):
        print("Event handler 'FieldChanged' not implemented!")
        event.Skip()

    def SetRunnerTeam(self, event):
        print("Event handler 'SetRunnerTeam' not implemented!")
        event.Skip()

    def SetCourse(self, event):
        print("Event handler 'SetCourse' not implemented!")
        event.Skip()

    def SetOverride(self, event):
        print("Event handler 'SetOverride' not implemented!")
        event.Skip()

    def SetComplete(self, event):
        print("Event handler 'SetComplete' not implemented!")
        event.Skip()

    def ChangePunch(self, event):
        print("Event handler 'ChangePunch' not implemented!")
        event.Skip()

    def ExitPunch(self, event):
        print("Event handler 'ExitPunch' not implemented!")
        event.Skip()

    def EditPunch(self, event):
        print("Event handler 'EditPunch' not implemented!")
        event.Skip()


class ReadoutRunPanel(BaseRunPanel):
    def __init__(self, *args, **kwds):
        kwds["style"] = kwds.get("style", 0) | wx.TAB_TRAVERSAL
        BaseRunPanel.__init__(self, *args, **kwds)

        sizer_3 = wx.BoxSizer(wx.VERTICAL)

        self.progress_bar = wx.Gauge(self, wx.ID_ANY, 10)
        sizer_3.Add(self.progress_bar, 0, wx.ALL | wx.EXPAND, 5)

        self.progress_text = wx.StaticText(self, wx.ID_ANY, "Reading Card data...")
        sizer_3.Add(self.progress_text, 0, wx.ALL, 5)

        self.print_checkbox = wx.CheckBox(self, wx.ID_ANY, "Print run")
        sizer_3.Add(self.print_checkbox, 0, wx.ALL, 2)

        sizer_12 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_3.Add(sizer_12, 1, wx.EXPAND, 0)

        sizer_15 = wx.BoxSizer(wx.VERTICAL)
        sizer_12.Add(sizer_15, 1, wx.EXPAND, 0)

        sizer_11 = wx.StaticBoxSizer(wx.StaticBox(self, wx.ID_ANY, "Runner Information"), wx.VERTICAL)
        sizer_15.Add(sizer_11, 1, wx.ALL | wx.EXPAND, 5)

        label_20_copy_copy = wx.StaticText(self, wx.ID_ANY, "Number:")
        sizer_11.Add(label_20_copy_copy, 0, wx.ALL, 2)

        self.runner_number = wx.StaticText(self, wx.ID_ANY, "101A")
        self.runner_number.SetFont(wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        sizer_11.Add(self.runner_number, 0, wx.ALL, 2)

        sizer_11.Add((20, 10), 0, 0, 0)

        self.label_6 = wx.StaticText(self, wx.ID_ANY, "Category:")
        sizer_11.Add(self.label_6, 0, wx.ALL, 2)

        self.runner_category = wx.StaticText(self, wx.ID_ANY, "HAM")
        self.runner_category.SetFont(wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        sizer_11.Add(self.runner_category, 0, wx.ALL, 2)

        sizer_11.Add((20, 10), 0, 0, 0)

        label_20_copy_1 = wx.StaticText(self, wx.ID_ANY, "Runner:")
        sizer_11.Add(label_20_copy_1, 0, wx.ALL, 2)

        self.runner_name = wx.StaticText(self, wx.ID_ANY, "Gaudenz Steinlin")
        self.runner_name.SetFont(wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        sizer_11.Add(self.runner_name, 0, wx.ALL, 2)

        sizer_11.Add((20, 10), 0, 0, 0)

        label_22_copy = wx.StaticText(self, wx.ID_ANY, "Team:")
        sizer_11.Add(label_22_copy, 0, wx.ALL, 2)

        self.runner_team = wx.StaticText(self, wx.ID_ANY, u"UBOL 3 \"saugrün\"")
        self.runner_team.SetFont(wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        sizer_11.Add(self.runner_team, 0, wx.ALL, 2)

        sizer_11.Add((20, 10), 0, 0, 0)

        label_24_copy = wx.StaticText(self, wx.ID_ANY, "SI-Card:")
        sizer_11.Add(label_24_copy, 0, wx.ALL, 2)

        self.runner_sicard = wx.StaticText(self, wx.ID_ANY, "654324")
        self.runner_sicard.SetFont(wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        sizer_11.Add(self.runner_sicard, 0, wx.ALL, 2)

        sizer_17 = wx.StaticBoxSizer(wx.StaticBox(self, wx.ID_ANY, "Validation and Scoreing"), wx.VERTICAL)
        sizer_15.Add(sizer_17, 1, wx.ALL | wx.EXPAND, 5)

        label_4_copy = wx.StaticText(self, wx.ID_ANY, "Run Validation:")
        sizer_17.Add(label_4_copy, 0, wx.ALL, 2)

        self.run_validation = wx.StaticText(self, wx.ID_ANY, "OK")
        self.run_validation.SetForegroundColour(wx.Colour(0, 255, 0))
        self.run_validation.SetFont(wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        sizer_17.Add(self.run_validation, 0, wx.ALL, 2)

        sizer_17.Add((10, 10), 1, 0, 0)

        label_6_copy_1 = wx.StaticText(self, wx.ID_ANY, "Team Validation:")
        sizer_17.Add(label_6_copy_1, 0, wx.ALL, 2)

        self.team_validation = wx.StaticText(self, wx.ID_ANY, "not yet finished")
        self.team_validation.SetForegroundColour(wx.Colour(255, 0, 0))
        self.team_validation.SetFont(wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        sizer_17.Add(self.team_validation, 0, wx.ALL, 2)

        sizer_17.Add((10, 10), 1, 0, 0)

        label_6_copy_copy = wx.StaticText(self, wx.ID_ANY, "Score:")
        sizer_17.Add(label_6_copy_copy, 0, wx.ALL, 2)

        self.run_score = wx.StaticText(self, wx.ID_ANY, "1:05:23")
        self.run_score.SetFont(wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        sizer_17.Add(self.run_score, 0, wx.ALL, 2)

        sizer_17.Add((10, 10), 1, 0, 0)

        label_6_copy_copy_copy = wx.StaticText(self, wx.ID_ANY, "Team Score:")
        sizer_17.Add(label_6_copy_copy_copy, 0, wx.ALL, 2)

        self.team_score = wx.StaticText(self, wx.ID_ANY, "Runs: 21, Time: 9:04:32")
        self.team_score.SetFont(wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        sizer_17.Add(self.team_score, 0, wx.ALL, 2)

        sizer_14 = wx.StaticBoxSizer(wx.StaticBox(self, wx.ID_ANY, "Run Information"), wx.VERTICAL)
        sizer_12.Add(sizer_14, 1, wx.ALL | wx.EXPAND, 5)

        sizer_18 = wx.GridSizer(6, 2, 0, 0)
        sizer_14.Add(sizer_18, 0, wx.EXPAND, 0)

        self.label_8 = wx.StaticText(self, wx.ID_ANY, "Course code:")
        sizer_18.Add(self.label_8, 0, wx.ALL, 2)

        label_24_copy_copy = wx.StaticText(self, wx.ID_ANY, "Run ID:")
        sizer_18.Add(label_24_copy_copy, 0, wx.ALL, 2)

        self.course = wx.StaticText(self, wx.ID_ANY, "LEN5")
        self.course.SetFont(wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        sizer_18.Add(self.course, 0, wx.ALL, 2)

        self.run_id = wx.StaticText(self, wx.ID_ANY, "1234")
        self.run_id.SetFont(wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        sizer_18.Add(self.run_id, 0, wx.ALL, 2)

        self.label_5_copy = wx.StaticText(self, wx.ID_ANY, "Clear time:")
        sizer_18.Add(self.label_5_copy, 0, wx.ALL, 2)

        self.label_7_copy_2 = wx.StaticText(self, wx.ID_ANY, "Check time:")
        sizer_18.Add(self.label_7_copy_2, 0, wx.ALL, 2)

        self.clear_time = wx.StaticText(self, wx.ID_ANY, "2008-05-04 11:02:54")
        self.clear_time.SetFont(wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        sizer_18.Add(self.clear_time, 0, wx.ALL, 2)

        self.check_time = wx.StaticText(self, wx.ID_ANY, "2008-05-04 11:03:01")
        self.check_time.SetFont(wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        sizer_18.Add(self.check_time, 0, wx.ALL, 2)

        self.label_7_copy_copy = wx.StaticText(self, wx.ID_ANY, "Start time:")
        sizer_18.Add(self.label_7_copy_copy, 0, wx.ALL, 2)

        self.label_7_copy_1_copy = wx.StaticText(self, wx.ID_ANY, "Finish time:")
        sizer_18.Add(self.label_7_copy_1_copy, 0, wx.ALL, 2)

        self.start_time = wx.StaticText(self, wx.ID_ANY, "2008-05-04 11:05:29")
        self.start_time.SetFont(wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        sizer_18.Add(self.start_time, 0, wx.ALL, 2)

        self.finish_time = wx.StaticText(self, wx.ID_ANY, "2008-05-04 11:58:01")
        self.finish_time.SetFont(wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        sizer_18.Add(self.finish_time, 0, wx.ALL, 2)

        sizer_14.Add((20, 20), 0, 0, 0)

        self.punches_grid = wx.grid.Grid(self, wx.ID_ANY, size=(1, 1))
        self.punches_grid.CreateGrid(0, 7)
        self.punches_grid.EnableEditing(0)
        self.punches_grid.EnableDragColSize(0)
        self.punches_grid.EnableDragRowSize(0)
        self.punches_grid.EnableDragGridSize(0)
        self.punches_grid.SetColLabelValue(0, "Nr.")
        self.punches_grid.SetColLabelValue(1, "Control")
        self.punches_grid.SetColLabelValue(2, "SI")
        self.punches_grid.SetColLabelValue(3, "Card Punchtime")
        self.punches_grid.SetColLabelValue(4, "Manual Punchtime")
        self.punches_grid.SetColLabelValue(5, "Ignore")
        self.punches_grid.SetColLabelValue(6, "")
        sizer_14.Add(self.punches_grid, 1, wx.EXPAND, 0)

        self.SetSizer(sizer_3)
        sizer_3.Fit(self)

        self.Layout()


class ReportsPanel(wx.Panel):
    def __init__(self, *args, **kwds):
        kwds["style"] = kwds.get("style", 0) | wx.TAB_TRAVERSAL
        wx.Panel.__init__(self, *args, **kwds)

        sizer_33 = wx.BoxSizer(wx.VERTICAL)

        sizer_34 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_33.Add(sizer_34, 0, wx.EXPAND, 0)

        self.label_10 = wx.StaticText(self, wx.ID_ANY, "Select Report:")
        sizer_34.Add(self.label_10, 0, wx.ALIGN_CENTER_VERTICAL, 0)

        self.report_combo = wx.ComboBox(self, wx.ID_ANY, choices=[], style=wx.CB_READONLY)
        sizer_34.Add(self.report_combo, 0, 0, 0)

        sizer_33.Add((20, 10), 0, 0, 0)

        self.run_grid = wx.grid.Grid(self, wx.ID_ANY, size=(1, 1))
        self.run_grid.CreateGrid(0, 10)
        self.run_grid.EnableEditing(0)
        self.run_grid.EnableDragRowSize(0)
        self.run_grid.EnableDragGridSize(0)
        self.run_grid.SetSelectionMode(wx.grid.Grid.SelectRows)
        self.run_grid.SetColLabelValue(0, "Run ID")
        self.run_grid.SetColLabelValue(1, "Course")
        self.run_grid.SetColLabelValue(2, "Runner")
        self.run_grid.SetColLabelValue(3, "SI-Card")
        self.run_grid.SetColLabelValue(4, "Team")
        self.run_grid.SetColLabelValue(5, "Start")
        self.run_grid.SetColLabelValue(6, "Finish")
        self.run_grid.SetColLabelValue(7, "Validation")
        self.run_grid.SetColLabelValue(8, "Team Validation")
        self.run_grid.SetColLabelValue(9, "Score")
        sizer_33.Add(self.run_grid, 1, wx.EXPAND, 0)

        self.SetSizer(sizer_33)
        sizer_33.Fit(self)

        self.Layout()

        self.Bind(wx.EVT_COMBOBOX, self.ChangeReport, self.report_combo)

    def ChangeReport(self, event):
        print("Event handler 'ChangeReport' not implemented!")
        event.Skip()


class RunnerPanel(wx.Panel):
    def __init__(self, *args, **kwds):
        kwds["style"] = kwds.get("style", 0) | wx.TAB_TRAVERSAL
        wx.Panel.__init__(self, *args, **kwds)

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        sizer_1.Add((0, 0), 0, 0, 0)

        self.SetSizer(sizer_1)
        sizer_1.Fit(self)

        self.Layout()

