#!/usr/bin/env python
# -*- coding: utf-8 -*-
#    import_teams.py - Import Data from go2ol.ch
#
#    Copyright (C) 2008  Gaudenz Steinlin <gaudenz@soziologie.ch>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

from optparse import OptionParser
import sys

import conf
from importer import Team24hImporter, TeamRelayImporter, SIRunImporter, OCADXMLCourseImporter, CSVCourseImporter

if __name__ == '__main__':
    # Read program options
    opt = OptionParser(usage = 'usage: %prog [options] command importfile', 
                       description = 'Available commands are \'teams\', \'runs\' and \'courses\'.')
    opt.add_option('-e', '--encoding', action='store', default='utf-8',
                   help='Encoding of the imported file.')
    opt.add_option('-f', '--format', action='store',
                   help="Format of the file. Currently supported for team imports: 24h, relay; for courses: xml, csv")
    (options, (command, filename)) = opt.parse_args()

    if command == 'teams':
        # Import teams
        if options.format == '24h':
            importer = Team24hImporter(filename, options.encoding)
        elif options.format == 'relay':
            importer = TeamRelayImporter(filename, options.encoding)
        else:
            print 'Unknown Team format identifier!'
            sys.exit(1)
    elif command == 'runs':
        # Import runs
        importer = SIRunImporter(filename, options.encoding)
    elif command == 'courses':
        # Import courses
        if options.format == 'xml':
            importer = OCADXMLCourseImporter(filename, False, False)
        elif options.format == 'csv':
            importer = CSVCourseImporter(filename, options.encoding)
        else:
            print 'Unknown Course format identifier!'
            sys.exit(1)
    else:
        print "Unknown command '%s'" % command
        exit(1)
        
    importer.import_data(conf.store)
    conf.store.commit()
